version: "3.8"
services:
  api:
    build:
      context: .
    ports:
      - "127.0.0.1:$API_PORT:8080"
    command: flask run --host 0.0.0.0 --port 8080
    container_name: "vtfconvert_web"
    environment:
      FLASK_APP: "main.py"
    restart: always
